name: Deploy to WordPress
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm i
      - run: npm run build
      - name: Upload dist to WP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.WP_HOST }}
          username: ${{ secrets.WP_USER }}
          password: ${{ secrets.WP_PASS }}
          local-dir: dist/
          server-dir: /public_html/wp-content/uploads/lens-comparison/
